### ISSUE TITLE
missing tdom

### ISSUE THREAD

**Issue by heinrichmartin** [efrecon/mini-tcl#4]
tcllib's rest package depends on tdom, but which seems not available:

```
tclsh-8.6.7 [] % package require rest
can't find package tdom
    while executing
"package require tdom"
    (file "/usr/lib/tcllib1.18/rest/rest.tcl" line 12)
    invoked from within
"source /usr/lib/tcllib1.18/rest/rest.tcl"
    ("package ifneeded rest 1.0.2" script)
    invoked from within
"package require rest"
```

**Comment by heinrichmartin** [comment]
A workaround is actually your tcl container, not mini-tcl. However, we are then looking at 465 MB instead of 18 MB.

Also, I tried to add it, but tdom is not available in Alpine repos. So this should probably be a ticket for Alpine...

**Comment by efrecon** [comment]
Yes. That would be a ticket for alpine and i would guess that this means
somebody providing the ground work for it. Are you in for it?

Den 21 dec. 2017 14:40 skrev "heinrichmartin" <notifications@github.com>:

**Comment by efrecon** [comment]
Now fixed, see: b4fc6fbe17aa7979cee93d3a616cb22dc417bcc0. Provided as part of `edge`, `latest` and `3.7`. Tell me if that did not work.

**Comment by heinrichmartin** [comment]
This is a nice surprise - didn't expect a fix after you confirmed it's missing in Alpine. Thank you!

**Comment by efrecon** [comment]
You are welcome! Working around it by compiling the package manually proved to be rather simple . It is also a nice addition as it could be the way to install more missing packages if necessary in the future.
